"""empty message

Revision ID: 18f12fcde068
Revises: 603dbfb4506a
Create Date: 2023-07-28 18:34:59.347776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f12fcde068'
down_revision = '603dbfb4506a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order__item', schema=None) as batch_op:
        batch_op.drop_constraint('order__item_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order__item_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('item_id')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order__item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order__item_order_id_fkey', 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key('order__item_item_id_fkey', 'item', ['item_id'], ['id'])

    # ### end Alembic commands ###
