"""empty message

Revision ID: 263c4ac3a29b
Revises: cfc491ed3154
Create Date: 2023-08-02 14:38:07.321269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263c4ac3a29b'
down_revision = 'cfc491ed3154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
