"""empty message

Revision ID: 44619765a9dd
Revises: d1493ae3d536
Create Date: 2023-07-28 12:22:15.771299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44619765a9dd'
down_revision = 'd1493ae3d536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
