"""empty message

Revision ID: 46bf875c261f
Revises: d6d22afc4f33
Create Date: 2023-07-27 19:29:43.582296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bf875c261f'
down_revision = 'd6d22afc4f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_phone',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_phone',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
