"""empty message

Revision ID: 603dbfb4506a
Revises: 9c216da4dd5e
Create Date: 2023-07-28 13:19:14.719282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603dbfb4506a'
down_revision = '9c216da4dd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_delivered', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('order_delivered')

    # ### end Alembic commands ###
