"""empty message

Revision ID: 6c3d628d301e
Revises: c40d3718e532
Create Date: 2023-07-28 12:02:31.269077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3d628d301e'
down_revision = 'c40d3718e532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
