"""empty message

Revision ID: c40d3718e532
Revises: 7eb68251001c
Create Date: 2023-07-28 11:58:27.084179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40d3718e532'
down_revision = '7eb68251001c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
