"""empty message

Revision ID: cfc491ed3154
Revises: b12193dba69d
Create Date: 2023-07-31 11:31:04.523746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc491ed3154'
down_revision = 'b12193dba69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order__item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order__item', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
