"""empty message

Revision ID: d1493ae3d536
Revises: b39a3f017c1b
Create Date: 2023-07-28 12:06:11.751916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1493ae3d536'
down_revision = 'b39a3f017c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
